import pygame

BPM_CHANGED_EVENT = pygame.USEREVENT + 1
BPM_TICK = pygame.USEREVENT + 2
BPM_HALF_TICK = pygame.USEREVENT + 3
DEMAND_CHANGE_BPM = pygame.USEREVENT + 4
DEMAND_CHANGE_TRACK_SIZE = pygame.USEREVENT + 5
DEMAND_CHANGE_SAMPLERATE = pygame.USEREVENT + 6